name: Production Pipeline

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup and Install Dependencies
      - name: Setup and Install Dependencies
        uses: ./.github/actions/setup
        with:
          node_version: "22.20.0"
          pnpm_version: "10.17.1"

      # Set Version Tag
      - name: Set Version Tag
        id: lib-version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      # Set Flag if Tag Exist
      - name: Set Flag if Tag Exist
        id: tag
        run: |
          echo "TAG_EXISTS=$(git ls-remote --tags origin refs/tags/v${{ steps.lib-version.outputs.VERSION }})" >> $GITHUB_OUTPUT

      - name: Extract latest changelog
        run: |
          awk '/^## [-1-9]+\.[0-9]+\.[0-9]+/ { if (found) exit; found=1 } found { print }' CHANGELOG.md > RELEASE_NOTES.md

      # Only push and release tag if it does not yet exist.
      - name: Release Tag
        if: steps.tag.outputs.TAG_EXISTS == ''
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_NOTES.md
          tag_name: v${{ steps.lib-version.outputs.VERSION }}
          draft: false
          prerelease: false
